config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :resumes
  root 'resumes#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resume.rb
# frozen_string_literal: true

class Resume < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/resumes_controller.rb
# frozen_string_literal: true

class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def edit
    @resume = Resume.find(params[:id])
  end

  def update
    @resume = Resume.find(params[:id])
    if @resume.update(resume_params)
      flash[:success] = 'Профиль обновлен'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render 'new'
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice: "The resume #{@resume.name} has been deleted."
  end

  private

  def resume_params
    params.require(:resume).permit(:name, :price, :time, :col, :date, :oblast)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/resumes_helper.rb
# frozen_string_literal: true

module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mass</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<div class="row">
  <div class="col-1"></div>
  <div class="col">
   <!-- Только CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Пакет JavaScript с Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</div>
<div class="col-1"></div>

  </div>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/edit.html.erb
<center>
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>
<div class = "well">
   <%= form_with model: @resume, url: resume_path(@resume), method: :patch, local: true do |f| %>
   <br/>
   <br/>
      <p>Имя</p>
      <%= f.text_field :name ,placeholder: "Имя"%>
      <br/>
      <p>Цена</p>
      <%= f.text_field :price ,placeholder: "Цена" %>
      <br/>
      <p>Время</p>
      <%= f.text_field :time ,placeholder: "Время"%>
      <br/>
      <p>Количество</p>
      <%= f.text_field :col ,placeholder: "Количество раз" %>
      <p>Область</p>
      <%= f.text_field :oblast ,placeholder: "Область массажа"%>
      <br/>
      <br/>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
</center>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />
<%= link_to "Новый посетитель", new_resume_path, class: "btn btn-primary" %>
<br />
<br />
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Имя</th>
         <th>Цена</th>
         <th>Область</th>
         <th>Время</th>
         <th>Пришел</th>
         <th>Дата</th>
         <th>удалить</th>
         <th>изменить</th>
      </tr>
   </thead>
   <tbody>
      <% @resumes.each do |resume| %>
         <tr>
            <td><%= resume.name %></td>
            <td><%= resume.price %>₽</td>
            <td><%= resume.oblast %></td>
            <td><%= resume.time %></td>
            <td><%= resume.col%></td>
            <td><%= resume.date %></td>
            <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-primary", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
            <td><%= link_to "Изминить", edit_resume_path(resume), class: 'btn btn-primary'%></td>
    		</tr>
      <% end %>
   </tbody>
</table>

app/views/resumes/new.html.erb
<center>
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>
<div class = "well">
   <%= form_for @resume, html: { multipart: true } do |f| %>
   <br/>
   <br/>
      <%= f.text_field :name ,placeholder: "Имя"%>
      <br/>
      <br/>
      <%= f.text_field :price ,placeholder: "Цена" %>
      <br/>
      <br/>
      <%= f.text_field :time ,placeholder: "Время"%>
      <br/>
      <br/>
      <%= f.text_field :oblast ,placeholder: "Область массажа"%>
      <br/>
      <br/>
      <%= f.text_field :col ,placeholder: "Количество раз" %>
      <br/>
      <br/>
      <%= f.label :Дата %>
      <%= f.date_field :date %>
      <br/>
      <br/>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
</center>